---
version: "3.8"
# yamllint disable rule:line-length

services:
  web:
    build: .
    image: my-webpage
    container_name: my-webpage-container
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - /certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"